### ISSUE TITLE
init: Walk user through package setup

### ISSUE THREAD

**Issue by martriay** [zeppelinos/labs#94] opened 2018-04-18 18:39 UTC
We should provide a friendly way for the user to set up its package providing details interactively instead of passing them as CLI params, just like `npm init` does:

https://github.com/npm/npm/blob/latest/lib/init.js
https://github.com/npm/init-package-json/blob/latest/init-package-json.js

**Comment by facuspagnuolo** [comment] 2018-06-07 14:23
Duplicate of https://github.com/zeppelinos/zos-cli/issues/11

**Closed by facuspagnuolo** 2018-06-07 14:23 UTC
